Authentication
SkillSprint/Athena-Backend pull request #5
Opened 2023-02-04 19:46 UTC by rahulshamkuwar

Implemented the Login and Register routes for the API. Routes can be accessed via the following:
```
/auth/login

/auth/register
```
Authentication has also been implemented with JWT tokens, so there is a test route for the tokens.
```
/auth/profile
```

Routes are also protected with validation based on DTOs created.

2023-02-04 19:53 UTC, rahulshamkuwar commented
Need to implement the test cases, forgot about that.

2023-02-11 17:32 UTC, rahulshamkuwar commented on src/auth/auth.controller.spec.ts
> +          new BadRequestException({
Change to Unauthorized

2023-02-11 17:32 UTC, rahulshamkuwar commented on src/auth/auth.service.ts
> +    return { message: "User succesfully created!" };
Return user object and sign with jwt

2023-02-11 17:32 UTC, rahulshamkuwar commented on src/auth/auth.controller.spec.ts
> +        statusCode: 400,
401, unauthorized

2023-02-11 17:32 UTC, rahulshamkuwar commented on src/auth/auth.service.ts
> +    const hashedPassword = await compareSync(payload.password, user.password);
use compare

2023-02-11 17:32 UTC, rahulshamkuwar commented on src/utils/constants.ts
> +import { SetMetadata } from "@nestjs/common";
Create new `errorMessages.ts` file with constants

2023-02-11 17:32 UTC, rahulshamkuwar commented on src/auth/auth.service.ts
> +          statusCode: 401,
400, Bad request

2023-02-11 17:32 UTC, rahulshamkuwar commented on src/auth/auth.service.ts
> +      if (error.code === "P2002") {
Use prisma object

2023-02-11 17:32 UTC, rahulshamkuwar commented on src/auth/auth.service.spec.ts
> +  });
dekete

2023-02-11 17:32 UTC, rahulshamkuwar commented on src/auth/auth.service.spec.ts
> +});
Add test cases for errors

2023-02-11 17:32 UTC, rahulshamkuwar commented on src/auth/dto/authorized_user.dto.ts
> +export class AuthorizedUserDto {
look into extending another dto

2023-02-11 17:32 UTC, rahulshamkuwar commented on src/users/users.service.ts
> +  }
implement soft and hard delete

2023-03-20 07:28 UTC, sspathare97 requested changes
Suber big PR- I may have overlooked some things due to sheer volume. I would encourage splitting them up into smaller PRs in the future.

2023-03-20 07:28 UTC, sspathare97 commented on src/auth/auth.controller.spec.ts
> +    expect(await controller.register(dto)).toEqual({
Define mockAuthService here to define the behavior inside the test case. Check if it's possible to reuse the module object and just pass a different value in each test case; make sure it doesn't affect other test cases because multiple tests are probably running in parallel. If the module can't be reused, define a module for each test case.

2023-03-20 07:28 UTC, sspathare97 commented on src/auth/auth.service.spec.ts
> +        if (where.email === "test2@email.com") {
The same comments apply here.

2023-03-20 07:28 UTC, sspathare97 commented on src/auth/auth.service.ts
> +      throw new UnauthorizedException();
Are we using a logging service? Since we're throwing the same error for no user and invalid password, there's no way to distinguish it from the frontend (which is a feature). In that case, we'd still like to know from the backend what went wrong when we try to debug (say, if an angry student comes to us). So we log an error message here, like `logger.error('User with ${email} not found');` Make sure the logs aren't too noisy.

2023-03-20 07:28 UTC, sspathare97 commented on src/auth/auth.service.ts
> +    const hashedPassword = await hash(pass, 10);
Just pass `payload.password` instead

2023-03-20 07:28 UTC, sspathare97 commented on src/auth/auth.service.ts
> +    const { password, ...result } = user;
^

2023-03-20 07:28 UTC, sspathare97 commented on src/auth/auth.service.ts
>      const { password: pass, ...input } = payload;
If not using the destructured password, [don't create a variable for it](https://stackoverflow.com/a/53443378/7145074).
```suggestion
    const input = (({ password, ...rest }) => rest)(user);
```

2023-03-20 07:28 UTC, sspathare97 commented on src/auth/auth.service.ts
>      const { password, ...result } = user;
^

2023-03-20 07:28 UTC, sspathare97 commented on src/database/schema.prisma
> +  TEACHERSASSISTANT
_ as separator?
It's Teaching Assistant

2023-03-20 07:28 UTC, sspathare97 commented on src/users/users.service.spec.ts
> +    ).toEqual(userArray[1]);
How does the returned user object match the same original user object?

2023-03-20 17:35 UTC, rahulshamkuwar commented on package.json
> +    "format": "prettier --write .",
Yeah there isn't. From what I saw, leaving it like that would only fix the content that's in the `src` folder with the `.ts` extensions and doesn't run on something like the contents of the `.vscode`.

2023-03-20 17:40 UTC, sspathare97 commented on package.json
> +    "format": "prettier --write .",
1. settings.json shouldn't be checked into git, users may want to customize their settings. Create a copy recommended-settings.json and check in that instead.
2. If you want prettier to format .vscode directory, add that in the format command.
```suggestion
    "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\" \".vscode/**/*.json\"",
```

2023-03-20 17:42 UTC, rahulshamkuwar commented on src/auth/auth.service.ts
> +      throw new UnauthorizedException();
Does `console.log` work? I looked for something like `logger.error` but couldn't find it built into JS. Is is some external library?

2023-03-20 17:44 UTC, sspathare97 commented on src/auth/auth.service.ts
> +      throw new UnauthorizedException();
https://docs.nestjs.com/techniques/logger

2023-03-20 17:47 UTC, rahulshamkuwar commented on package.json
> +    "format": "prettier --write .",
For `settings.json`, when you say checked into git, do you mean it should be ignored by git? Or is that for prettier?

2023-03-20 17:49 UTC, sspathare97 commented on package.json
> +    "format": "prettier --write .",
Checked in = added via git add

2023-03-20 17:56 UTC, sspathare97 commented on package.json
> +    "format": "prettier --write .",
We still probably want to check in tasks.json and others and recommended-settings.json
Here's how .gitignore should look-
```
// ignore all files
**/*.vscode/*
// except these listed here, don't ignore them, we want to check them in
!**/*.vscode/recommended-settings.json
!**/*.vscode/extensions.json
// tasks and launch and whatever
```

2023-03-20 18:03 UTC, rahulshamkuwar commented on src/auth/auth.service.ts
> +      throw new UnauthorizedException();
Should not finding a user/passwords not matching be an `error`? To me it makes more sense to use `log` or `verbose` instead. I would assume `error`s would be actual errors that occur from the codebase, not something where the user input is invalid.

2023-03-20 18:08 UTC, rahulshamkuwar commented on src/users/users.service.ts
> +  }
Will be implemented in a separate PR.

2023-03-20 18:53 UTC, sspathare97 commented on src/auth/auth.service.ts
> +      throw new UnauthorizedException();
That is perfect.

2023-03-20 18:53 UTC, sspathare97 commented on src/users/users.service.ts
> +  }
Thank you

2023-03-20 19:02 UTC, sspathare97 commented on package.json
> +    "format": "prettier --write .",
You can find them online and pick the ones the whole team agrees are recommended. A couple I use are autoSave and formatOnSave

2023-05-21 20:58 UTC, catalyze8173 approved these changes

2023-05-21 21:02 UTC, sspathare97 approved these changes

2023-05-21 21:06 UTC, merged